user:
    type:     rest
    resource: "@AppBundle/Controller/UserController.php"

feature:
    type:     rest
    resource: "@AppBundle/Controller/FeatureController.php"

quest:
    type:     rest
    parent:   feature
    resource: "@AppBundle/Controller/QuestController.php"

step:
    type:     rest
    parent:   quest
    resource: "@AppBundle/Controller/StepController.php"