default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

feature:
    type:     rest
    resource: "@AppBundle/Controller/FeatureController.php"
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"